/* Copyright (c) 2008 Nokia Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This file is automatically generated by Symbian/src/gendataexports.py.
 * Do not edit this file manually. */

#include "Python.h"
#define PYTHON_AST_NO_MACRO
#include "Python-ast.h"
#undef PYTHON_AST_NO_MACRO
#include "frameobject.h"
#include "pygetopt.h"
#include "node.h"
#include "token.h"
#include "graminit.h"
#include "code.h"
#include "compile.h"
#include "symtable.h"


EXPORT_C PyTypeObject *
__DATAEXPORT_PyBool_Type () { return &PyBool_Type; }

EXPORT_C PyIntObject *
__DATAEXPORT__Py_ZeroStruct () { return &_Py_ZeroStruct; }

EXPORT_C PyIntObject *
__DATAEXPORT__Py_TrueStruct () { return &_Py_TrueStruct; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyBuffer_Type () { return &PyBuffer_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyCell_Type () { return &PyCell_Type; }

EXPORT_C int *
__DATAEXPORT__Py_CheckRecursionLimit () { return &_Py_CheckRecursionLimit; }

EXPORT_C volatile int *
__DATAEXPORT__Py_Ticker () { return &_Py_Ticker; }

EXPORT_C int *
__DATAEXPORT__Py_CheckInterval () { return &_Py_CheckInterval; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyClass_Type () { return &PyClass_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyInstance_Type () { return &PyInstance_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyMethod_Type () { return &PyMethod_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyCObject_Type () { return &PyCObject_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyCode_Type () { return &PyCode_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyComplex_Type () { return &PyComplex_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyWrapperDescr_Type () { return &PyWrapperDescr_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyProperty_Type () { return &PyProperty_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyDict_Type () { return &PyDict_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyEnum_Type () { return &PyEnum_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyReversed_Type () { return &PyReversed_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyFile_Type () { return &PyFile_Type; }

EXPORT_C const char * *
__DATAEXPORT_Py_FileSystemDefaultEncoding () { return &Py_FileSystemDefaultEncoding; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyFloat_Type () { return &PyFloat_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyFrame_Type () { return &PyFrame_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyFunction_Type () { return &PyFunction_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyClassMethod_Type () { return &PyClassMethod_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyStaticMethod_Type () { return &PyStaticMethod_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyGen_Type () { return &PyGen_Type; }

EXPORT_C struct _inittab * *
__DATAEXPORT_PyImport_Inittab () { return &PyImport_Inittab; }

EXPORT_C struct _frozen * *
__DATAEXPORT_PyImport_FrozenModules () { return &PyImport_FrozenModules; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyInt_Type () { return &PyInt_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PySeqIter_Type () { return &PySeqIter_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyCallIter_Type () { return &PyCallIter_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyList_Type () { return &PyList_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyLong_Type () { return &PyLong_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyCFunction_Type () { return &PyCFunction_Type; }

EXPORT_C char * *
__DATAEXPORT__Py_PackageContext () { return &_Py_PackageContext; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyModule_Type () { return &PyModule_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyType_Type () { return &PyType_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyBaseObject_Type () { return &PyBaseObject_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PySuper_Type () { return &PySuper_Type; }

#ifdef Py_REF_DEBUG
EXPORT_C Py_ssize_t *
__DATAEXPORT__Py_RefTotal () { return &_Py_RefTotal; }
#endif

EXPORT_C PyObject *
__DATAEXPORT__Py_NoneStruct () { return &_Py_NoneStruct; }

EXPORT_C PyObject *
__DATAEXPORT__Py_NotImplementedStruct () { return &_Py_NotImplementedStruct; }

EXPORT_C int *
__DATAEXPORT__PyTrash_delete_nesting () { return &_PyTrash_delete_nesting; }

EXPORT_C PyObject * *
__DATAEXPORT__PyTrash_delete_later () { return &_PyTrash_delete_later; }

EXPORT_C int *
__DATAEXPORT_Py_DebugFlag () { return &Py_DebugFlag; }

EXPORT_C int *
__DATAEXPORT_Py_VerboseFlag () { return &Py_VerboseFlag; }

EXPORT_C int *
__DATAEXPORT_Py_InteractiveFlag () { return &Py_InteractiveFlag; }

EXPORT_C int *
__DATAEXPORT_Py_OptimizeFlag () { return &Py_OptimizeFlag; }

EXPORT_C int *
__DATAEXPORT_Py_NoSiteFlag () { return &Py_NoSiteFlag; }

EXPORT_C int *
__DATAEXPORT_Py_UseClassExceptionsFlag () { return &Py_UseClassExceptionsFlag; }

EXPORT_C int *
__DATAEXPORT_Py_FrozenFlag () { return &Py_FrozenFlag; }

EXPORT_C int *
__DATAEXPORT_Py_TabcheckFlag () { return &Py_TabcheckFlag; }

EXPORT_C int *
__DATAEXPORT_Py_UnicodeFlag () { return &Py_UnicodeFlag; }

EXPORT_C int *
__DATAEXPORT_Py_IgnoreEnvironmentFlag () { return &Py_IgnoreEnvironmentFlag; }

EXPORT_C int *
__DATAEXPORT_Py_DivisionWarningFlag () { return &Py_DivisionWarningFlag; }

EXPORT_C int *
__DATAEXPORT__Py_QnewFlag () { return &_Py_QnewFlag; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_BaseException () { return &PyExc_BaseException; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_Exception () { return &PyExc_Exception; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_StopIteration () { return &PyExc_StopIteration; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_GeneratorExit () { return &PyExc_GeneratorExit; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_StandardError () { return &PyExc_StandardError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_ArithmeticError () { return &PyExc_ArithmeticError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_LookupError () { return &PyExc_LookupError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_AssertionError () { return &PyExc_AssertionError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_AttributeError () { return &PyExc_AttributeError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_EOFError () { return &PyExc_EOFError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_FloatingPointError () { return &PyExc_FloatingPointError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_EnvironmentError () { return &PyExc_EnvironmentError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_IOError () { return &PyExc_IOError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_OSError () { return &PyExc_OSError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_ImportError () { return &PyExc_ImportError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_IndexError () { return &PyExc_IndexError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_KeyError () { return &PyExc_KeyError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_KeyboardInterrupt () { return &PyExc_KeyboardInterrupt; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_MemoryError () { return &PyExc_MemoryError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_NameError () { return &PyExc_NameError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_OverflowError () { return &PyExc_OverflowError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_RuntimeError () { return &PyExc_RuntimeError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_NotImplementedError () { return &PyExc_NotImplementedError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_SyntaxError () { return &PyExc_SyntaxError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_IndentationError () { return &PyExc_IndentationError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_TabError () { return &PyExc_TabError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_ReferenceError () { return &PyExc_ReferenceError; }

#ifdef SYMBIAN
EXPORT_C PyObject * *
__DATAEXPORT_PyExc_SymbianError () { return &PyExc_SymbianError; }
#endif

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_SystemError () { return &PyExc_SystemError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_SystemExit () { return &PyExc_SystemExit; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_TypeError () { return &PyExc_TypeError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_UnboundLocalError () { return &PyExc_UnboundLocalError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_UnicodeError () { return &PyExc_UnicodeError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_UnicodeEncodeError () { return &PyExc_UnicodeEncodeError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_UnicodeDecodeError () { return &PyExc_UnicodeDecodeError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_UnicodeTranslateError () { return &PyExc_UnicodeTranslateError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_ValueError () { return &PyExc_ValueError; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_ZeroDivisionError () { return &PyExc_ZeroDivisionError; }

#ifdef MS_WINDOWS
EXPORT_C PyObject * *
__DATAEXPORT_PyExc_WindowsError () { return &PyExc_WindowsError; }
#endif

#ifdef __VMS
EXPORT_C PyObject * *
__DATAEXPORT_PyExc_VMSError () { return &PyExc_VMSError; }
#endif

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_MemoryErrorInst () { return &PyExc_MemoryErrorInst; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_Warning () { return &PyExc_Warning; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_UserWarning () { return &PyExc_UserWarning; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_DeprecationWarning () { return &PyExc_DeprecationWarning; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_PendingDeprecationWarning () { return &PyExc_PendingDeprecationWarning; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_SyntaxWarning () { return &PyExc_SyntaxWarning; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_RuntimeWarning () { return &PyExc_RuntimeWarning; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_FutureWarning () { return &PyExc_FutureWarning; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_ImportWarning () { return &PyExc_ImportWarning; }

EXPORT_C PyObject * *
__DATAEXPORT_PyExc_UnicodeWarning () { return &PyExc_UnicodeWarning; }

EXPORT_C int *
__DATAEXPORT__PyOS_opterr () { return &_PyOS_opterr; }

EXPORT_C int *
__DATAEXPORT__PyOS_optind () { return &_PyOS_optind; }

EXPORT_C char * *
__DATAEXPORT__PyOS_optarg () { return &_PyOS_optarg; }

EXPORT_C PyThreadState * *
__DATAEXPORT__PyThreadState_Current () { return &_PyThreadState_Current; }

EXPORT_C PyThreadFrameGetter *
__DATAEXPORT__PyThreadState_GetFrame () { return &_PyThreadState_GetFrame; }

EXPORT_C t_PyOS_InputHook *
__DATAEXPORT_PyOS_InputHook () { return &PyOS_InputHook; }

EXPORT_C t_PyOS_ReadlineFunctionPointer *
__DATAEXPORT_PyOS_ReadlineFunctionPointer () { return &PyOS_ReadlineFunctionPointer; }

EXPORT_C PyThreadState* *
__DATAEXPORT__PyOS_ReadlineTState () { return &_PyOS_ReadlineTState; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyRange_Type () { return &PyRange_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PySet_Type () { return &PySet_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyFrozenSet_Type () { return &PyFrozenSet_Type; }

EXPORT_C PyObject *
__DATAEXPORT__Py_EllipsisObject () { return &_Py_EllipsisObject; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PySlice_Type () { return &PySlice_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyBaseString_Type () { return &PyBaseString_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyString_Type () { return &PyString_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PySTEntry_Type () { return &PySTEntry_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyTraceBack_Type () { return &PyTraceBack_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyTuple_Type () { return &PyTuple_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT_PyUnicode_Type () { return &PyUnicode_Type; }

EXPORT_C PyTypeObject *
__DATAEXPORT__PyWeakref_RefType () { return &_PyWeakref_RefType; }

EXPORT_C PyTypeObject *
__DATAEXPORT__PyWeakref_ProxyType () { return &_PyWeakref_ProxyType; }

EXPORT_C PyTypeObject *
__DATAEXPORT__PyWeakref_CallableProxyType () { return &_PyWeakref_CallableProxyType; }

EXPORT_C t__Py_SwappedOp *
__DATAEXPORT__Py_SwappedOp () { return &_Py_SwappedOp; }

EXPORT_C t__PyParser_TokenNames *
__DATAEXPORT__PyParser_TokenNames () { return &_PyParser_TokenNames; }

EXPORT_C t__PyLong_DigitValue *
__DATAEXPORT__PyLong_DigitValue () { return &_PyLong_DigitValue; }
