/* Copyright (c) 2008 Nokia Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This file is automatically generated by Symbian/src/gendataexports.py.
 * Do not edit this file manually. */

#ifndef DATAEXPORTS_H
#define DATAEXPORTS_H

#ifndef Py_BUILD_CORE
#ifdef __cplusplus
extern "C" {
#endif

#include "Python.h"
#define PYTHON_AST_NO_MACRO
#include "Python-ast.h"
#undef PYTHON_AST_NO_MACRO
#include "frameobject.h"
#include "pygetopt.h"
#include "node.h"
#include "token.h"
#include "code.h"
#include "compile.h"
#include "symtable.h"


#define PyBool_Type (*__DATAEXPORT_PyBool_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyBool_Type ();

#define _Py_ZeroStruct (*__DATAEXPORT__Py_ZeroStruct())

__declspec(dllimport) PyIntObject *__DATAEXPORT__Py_ZeroStruct ();

#define _Py_TrueStruct (*__DATAEXPORT__Py_TrueStruct())

__declspec(dllimport) PyIntObject *__DATAEXPORT__Py_TrueStruct ();

#define PyBuffer_Type (*__DATAEXPORT_PyBuffer_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyBuffer_Type ();

#define PyCell_Type (*__DATAEXPORT_PyCell_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyCell_Type ();

#define _Py_CheckRecursionLimit (*__DATAEXPORT__Py_CheckRecursionLimit())

__declspec(dllimport) int *__DATAEXPORT__Py_CheckRecursionLimit ();

#define _Py_Ticker (*__DATAEXPORT__Py_Ticker())

__declspec(dllimport) volatile int *__DATAEXPORT__Py_Ticker ();

#define _Py_CheckInterval (*__DATAEXPORT__Py_CheckInterval())

__declspec(dllimport) int *__DATAEXPORT__Py_CheckInterval ();

#define PyClass_Type (*__DATAEXPORT_PyClass_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyClass_Type ();

#define PyInstance_Type (*__DATAEXPORT_PyInstance_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyInstance_Type ();

#define PyMethod_Type (*__DATAEXPORT_PyMethod_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyMethod_Type ();

#define PyCObject_Type (*__DATAEXPORT_PyCObject_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyCObject_Type ();

#define PyCode_Type (*__DATAEXPORT_PyCode_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyCode_Type ();

#define PyComplex_Type (*__DATAEXPORT_PyComplex_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyComplex_Type ();

#define PyWrapperDescr_Type (*__DATAEXPORT_PyWrapperDescr_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyWrapperDescr_Type ();

#define PyProperty_Type (*__DATAEXPORT_PyProperty_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyProperty_Type ();

#define PyDict_Type (*__DATAEXPORT_PyDict_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyDict_Type ();

#define PyEnum_Type (*__DATAEXPORT_PyEnum_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyEnum_Type ();

#define PyReversed_Type (*__DATAEXPORT_PyReversed_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyReversed_Type ();

#define PyFile_Type (*__DATAEXPORT_PyFile_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyFile_Type ();

#define Py_FileSystemDefaultEncoding (*__DATAEXPORT_Py_FileSystemDefaultEncoding())

__declspec(dllimport) const char * *__DATAEXPORT_Py_FileSystemDefaultEncoding ();

#define PyFloat_Type (*__DATAEXPORT_PyFloat_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyFloat_Type ();

#define PyFrame_Type (*__DATAEXPORT_PyFrame_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyFrame_Type ();

#define PyFunction_Type (*__DATAEXPORT_PyFunction_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyFunction_Type ();

#define PyClassMethod_Type (*__DATAEXPORT_PyClassMethod_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyClassMethod_Type ();

#define PyStaticMethod_Type (*__DATAEXPORT_PyStaticMethod_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyStaticMethod_Type ();

#define PyGen_Type (*__DATAEXPORT_PyGen_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyGen_Type ();

#define PyImport_Inittab (*__DATAEXPORT_PyImport_Inittab())

__declspec(dllimport) struct _inittab * *__DATAEXPORT_PyImport_Inittab ();

#define PyImport_FrozenModules (*__DATAEXPORT_PyImport_FrozenModules())

__declspec(dllimport) struct _frozen * *__DATAEXPORT_PyImport_FrozenModules ();

#define PyInt_Type (*__DATAEXPORT_PyInt_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyInt_Type ();

#define PySeqIter_Type (*__DATAEXPORT_PySeqIter_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PySeqIter_Type ();

#define PyCallIter_Type (*__DATAEXPORT_PyCallIter_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyCallIter_Type ();

#define PyList_Type (*__DATAEXPORT_PyList_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyList_Type ();

#define PyLong_Type (*__DATAEXPORT_PyLong_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyLong_Type ();

#define PyCFunction_Type (*__DATAEXPORT_PyCFunction_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyCFunction_Type ();

#define _Py_PackageContext (*__DATAEXPORT__Py_PackageContext())

__declspec(dllimport) char * *__DATAEXPORT__Py_PackageContext ();

#define PyModule_Type (*__DATAEXPORT_PyModule_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyModule_Type ();

#define PyType_Type (*__DATAEXPORT_PyType_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyType_Type ();

#define PyBaseObject_Type (*__DATAEXPORT_PyBaseObject_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyBaseObject_Type ();

#define PySuper_Type (*__DATAEXPORT_PySuper_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PySuper_Type ();

#ifdef Py_REF_DEBUG
#define _Py_RefTotal (*__DATAEXPORT__Py_RefTotal())

__declspec(dllimport) Py_ssize_t *__DATAEXPORT__Py_RefTotal ();
#endif

#define _Py_NoneStruct (*__DATAEXPORT__Py_NoneStruct())

__declspec(dllimport) PyObject *__DATAEXPORT__Py_NoneStruct ();

#define _Py_NotImplementedStruct (*__DATAEXPORT__Py_NotImplementedStruct())

__declspec(dllimport) PyObject *__DATAEXPORT__Py_NotImplementedStruct ();

#define _PyTrash_delete_nesting (*__DATAEXPORT__PyTrash_delete_nesting())

__declspec(dllimport) int *__DATAEXPORT__PyTrash_delete_nesting ();

#define _PyTrash_delete_later (*__DATAEXPORT__PyTrash_delete_later())

__declspec(dllimport) PyObject * *__DATAEXPORT__PyTrash_delete_later ();

#define Py_DebugFlag (*__DATAEXPORT_Py_DebugFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_DebugFlag ();

#define Py_VerboseFlag (*__DATAEXPORT_Py_VerboseFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_VerboseFlag ();

#define Py_InteractiveFlag (*__DATAEXPORT_Py_InteractiveFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_InteractiveFlag ();

#define Py_OptimizeFlag (*__DATAEXPORT_Py_OptimizeFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_OptimizeFlag ();

#define Py_NoSiteFlag (*__DATAEXPORT_Py_NoSiteFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_NoSiteFlag ();

#define Py_UseClassExceptionsFlag (*__DATAEXPORT_Py_UseClassExceptionsFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_UseClassExceptionsFlag ();

#define Py_FrozenFlag (*__DATAEXPORT_Py_FrozenFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_FrozenFlag ();

#define Py_TabcheckFlag (*__DATAEXPORT_Py_TabcheckFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_TabcheckFlag ();

#define Py_UnicodeFlag (*__DATAEXPORT_Py_UnicodeFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_UnicodeFlag ();

#define Py_IgnoreEnvironmentFlag (*__DATAEXPORT_Py_IgnoreEnvironmentFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_IgnoreEnvironmentFlag ();

#define Py_DivisionWarningFlag (*__DATAEXPORT_Py_DivisionWarningFlag())

__declspec(dllimport) int *__DATAEXPORT_Py_DivisionWarningFlag ();

#define _Py_QnewFlag (*__DATAEXPORT__Py_QnewFlag())

__declspec(dllimport) int *__DATAEXPORT__Py_QnewFlag ();

#define PyExc_BaseException (*__DATAEXPORT_PyExc_BaseException())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_BaseException ();

#define PyExc_Exception (*__DATAEXPORT_PyExc_Exception())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_Exception ();

#define PyExc_StopIteration (*__DATAEXPORT_PyExc_StopIteration())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_StopIteration ();

#define PyExc_GeneratorExit (*__DATAEXPORT_PyExc_GeneratorExit())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_GeneratorExit ();

#define PyExc_StandardError (*__DATAEXPORT_PyExc_StandardError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_StandardError ();

#define PyExc_ArithmeticError (*__DATAEXPORT_PyExc_ArithmeticError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_ArithmeticError ();

#define PyExc_LookupError (*__DATAEXPORT_PyExc_LookupError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_LookupError ();

#define PyExc_AssertionError (*__DATAEXPORT_PyExc_AssertionError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_AssertionError ();

#define PyExc_AttributeError (*__DATAEXPORT_PyExc_AttributeError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_AttributeError ();

#define PyExc_EOFError (*__DATAEXPORT_PyExc_EOFError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_EOFError ();

#define PyExc_FloatingPointError (*__DATAEXPORT_PyExc_FloatingPointError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_FloatingPointError ();

#define PyExc_EnvironmentError (*__DATAEXPORT_PyExc_EnvironmentError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_EnvironmentError ();

#define PyExc_IOError (*__DATAEXPORT_PyExc_IOError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_IOError ();

#define PyExc_OSError (*__DATAEXPORT_PyExc_OSError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_OSError ();

#define PyExc_ImportError (*__DATAEXPORT_PyExc_ImportError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_ImportError ();

#define PyExc_IndexError (*__DATAEXPORT_PyExc_IndexError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_IndexError ();

#define PyExc_KeyError (*__DATAEXPORT_PyExc_KeyError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_KeyError ();

#define PyExc_KeyboardInterrupt (*__DATAEXPORT_PyExc_KeyboardInterrupt())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_KeyboardInterrupt ();

#define PyExc_MemoryError (*__DATAEXPORT_PyExc_MemoryError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_MemoryError ();

#define PyExc_NameError (*__DATAEXPORT_PyExc_NameError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_NameError ();

#define PyExc_OverflowError (*__DATAEXPORT_PyExc_OverflowError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_OverflowError ();

#define PyExc_RuntimeError (*__DATAEXPORT_PyExc_RuntimeError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_RuntimeError ();

#define PyExc_NotImplementedError (*__DATAEXPORT_PyExc_NotImplementedError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_NotImplementedError ();

#define PyExc_SyntaxError (*__DATAEXPORT_PyExc_SyntaxError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_SyntaxError ();

#define PyExc_IndentationError (*__DATAEXPORT_PyExc_IndentationError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_IndentationError ();

#define PyExc_TabError (*__DATAEXPORT_PyExc_TabError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_TabError ();

#define PyExc_ReferenceError (*__DATAEXPORT_PyExc_ReferenceError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_ReferenceError ();

#ifdef SYMBIAN
#define PyExc_SymbianError (*__DATAEXPORT_PyExc_SymbianError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_SymbianError ();
#endif

#define PyExc_SystemError (*__DATAEXPORT_PyExc_SystemError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_SystemError ();

#define PyExc_SystemExit (*__DATAEXPORT_PyExc_SystemExit())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_SystemExit ();

#define PyExc_TypeError (*__DATAEXPORT_PyExc_TypeError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_TypeError ();

#define PyExc_UnboundLocalError (*__DATAEXPORT_PyExc_UnboundLocalError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_UnboundLocalError ();

#define PyExc_UnicodeError (*__DATAEXPORT_PyExc_UnicodeError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_UnicodeError ();

#define PyExc_UnicodeEncodeError (*__DATAEXPORT_PyExc_UnicodeEncodeError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_UnicodeEncodeError ();

#define PyExc_UnicodeDecodeError (*__DATAEXPORT_PyExc_UnicodeDecodeError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_UnicodeDecodeError ();

#define PyExc_UnicodeTranslateError (*__DATAEXPORT_PyExc_UnicodeTranslateError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_UnicodeTranslateError ();

#define PyExc_ValueError (*__DATAEXPORT_PyExc_ValueError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_ValueError ();

#define PyExc_ZeroDivisionError (*__DATAEXPORT_PyExc_ZeroDivisionError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_ZeroDivisionError ();

#ifdef MS_WINDOWS
#define PyExc_WindowsError (*__DATAEXPORT_PyExc_WindowsError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_WindowsError ();
#endif

#ifdef __VMS
#define PyExc_VMSError (*__DATAEXPORT_PyExc_VMSError())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_VMSError ();
#endif

#define PyExc_MemoryErrorInst (*__DATAEXPORT_PyExc_MemoryErrorInst())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_MemoryErrorInst ();

#define PyExc_Warning (*__DATAEXPORT_PyExc_Warning())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_Warning ();

#define PyExc_UserWarning (*__DATAEXPORT_PyExc_UserWarning())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_UserWarning ();

#define PyExc_DeprecationWarning (*__DATAEXPORT_PyExc_DeprecationWarning())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_DeprecationWarning ();

#define PyExc_PendingDeprecationWarning (*__DATAEXPORT_PyExc_PendingDeprecationWarning())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_PendingDeprecationWarning ();

#define PyExc_SyntaxWarning (*__DATAEXPORT_PyExc_SyntaxWarning())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_SyntaxWarning ();

#define PyExc_RuntimeWarning (*__DATAEXPORT_PyExc_RuntimeWarning())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_RuntimeWarning ();

#define PyExc_FutureWarning (*__DATAEXPORT_PyExc_FutureWarning())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_FutureWarning ();

#define PyExc_ImportWarning (*__DATAEXPORT_PyExc_ImportWarning())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_ImportWarning ();

#define PyExc_UnicodeWarning (*__DATAEXPORT_PyExc_UnicodeWarning())

__declspec(dllimport) PyObject * *__DATAEXPORT_PyExc_UnicodeWarning ();

#define _PyOS_opterr (*__DATAEXPORT__PyOS_opterr())

__declspec(dllimport) int *__DATAEXPORT__PyOS_opterr ();

#define _PyOS_optind (*__DATAEXPORT__PyOS_optind())

__declspec(dllimport) int *__DATAEXPORT__PyOS_optind ();

#define _PyOS_optarg (*__DATAEXPORT__PyOS_optarg())

__declspec(dllimport) char * *__DATAEXPORT__PyOS_optarg ();

#define _PyThreadState_Current (*__DATAEXPORT__PyThreadState_Current())

__declspec(dllimport) PyThreadState * *__DATAEXPORT__PyThreadState_Current ();

#define _PyThreadState_GetFrame (*__DATAEXPORT__PyThreadState_GetFrame())

__declspec(dllimport) PyThreadFrameGetter *__DATAEXPORT__PyThreadState_GetFrame ();

#define PyOS_InputHook (*__DATAEXPORT_PyOS_InputHook())

__declspec(dllimport) t_PyOS_InputHook *__DATAEXPORT_PyOS_InputHook ();

#define PyOS_ReadlineFunctionPointer (*__DATAEXPORT_PyOS_ReadlineFunctionPointer())

__declspec(dllimport) t_PyOS_ReadlineFunctionPointer *__DATAEXPORT_PyOS_ReadlineFunctionPointer ();

#define _PyOS_ReadlineTState (*__DATAEXPORT__PyOS_ReadlineTState())

__declspec(dllimport) PyThreadState* *__DATAEXPORT__PyOS_ReadlineTState ();

#define PyRange_Type (*__DATAEXPORT_PyRange_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyRange_Type ();

#define PySet_Type (*__DATAEXPORT_PySet_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PySet_Type ();

#define PyFrozenSet_Type (*__DATAEXPORT_PyFrozenSet_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyFrozenSet_Type ();

#define _Py_EllipsisObject (*__DATAEXPORT__Py_EllipsisObject())

__declspec(dllimport) PyObject *__DATAEXPORT__Py_EllipsisObject ();

#define PySlice_Type (*__DATAEXPORT_PySlice_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PySlice_Type ();

#define PyBaseString_Type (*__DATAEXPORT_PyBaseString_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyBaseString_Type ();

#define PyString_Type (*__DATAEXPORT_PyString_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyString_Type ();

#define PySTEntry_Type (*__DATAEXPORT_PySTEntry_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PySTEntry_Type ();

#define PyTraceBack_Type (*__DATAEXPORT_PyTraceBack_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyTraceBack_Type ();

#define PyTuple_Type (*__DATAEXPORT_PyTuple_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyTuple_Type ();

#define PyUnicode_Type (*__DATAEXPORT_PyUnicode_Type())

__declspec(dllimport) PyTypeObject *__DATAEXPORT_PyUnicode_Type ();

#define _PyWeakref_RefType (*__DATAEXPORT__PyWeakref_RefType())

__declspec(dllimport) PyTypeObject *__DATAEXPORT__PyWeakref_RefType ();

#define _PyWeakref_ProxyType (*__DATAEXPORT__PyWeakref_ProxyType())

__declspec(dllimport) PyTypeObject *__DATAEXPORT__PyWeakref_ProxyType ();

#define _PyWeakref_CallableProxyType (*__DATAEXPORT__PyWeakref_CallableProxyType())

__declspec(dllimport) PyTypeObject *__DATAEXPORT__PyWeakref_CallableProxyType ();

#define _Py_SwappedOp (*__DATAEXPORT__Py_SwappedOp())

__declspec(dllimport) t__Py_SwappedOp *__DATAEXPORT__Py_SwappedOp ();

#define _PyParser_TokenNames (*__DATAEXPORT__PyParser_TokenNames())

__declspec(dllimport) t__PyParser_TokenNames *__DATAEXPORT__PyParser_TokenNames ();

#define _PyLong_DigitValue (*__DATAEXPORT__PyLong_DigitValue())

__declspec(dllimport) t__PyLong_DigitValue *__DATAEXPORT__PyLong_DigitValue ();


#ifdef __cplusplus
}
#endif

#endif /* Py_BUILD_CORE */

#endif /* DATAEXPORTS_H */
